{{- if .Values.metrics.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "monedula-gitops.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "monedula-gitops.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "monedula-gitops.selectorLabels" . | nindent 4 }}
  ports:
  - name: metrics
    port: {{ .Values.metrics.service.port }}
    targetPort: metrics
    protocol: TCP
{{- end }}
