apiVersion: gitops.monedula.dev/v1alpha1
kind: KafkaQuota
metadata:
  name: svc-quota
spec:
  clusterRef:
    name: shared
  entity:
    user: "User:svc-quota-user"
  limits:
    producerByteRate: 1048576
    consumerByteRate: 2097152
