apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gitops.monedula.dev_kafkaclusters.yaml
- gitops.monedula.dev_kafkatopics.yaml
- gitops.monedula.dev_kafkaaccesspolicies.yaml
- gitops.monedula.dev_kafkaquotas.yaml
- gitops.monedula.dev_kafkarolebindings.yaml
- gitops.monedula.dev_kafkausers.yaml
